name: "MetaShark"
guid: "9A19103F-16F7-4668-BE54-9A1E7A4F7556"
imageUrl: https://github.com/cxfksword/jellyfin-plugin-metashark/raw/main/doc/logo.png
version: "1.0.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "cxfksword"
overview: "jellyfin电影元数据插件"
description: >
  jellyfin电影元数据插件，影片信息只要从豆瓣获取，并由TMDB补充缺失的季数据和剧集数据。
category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.MetaShark.dll"
changelog: >
  NA
