name: "🏗️ Build Plugin"

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        id: dotnet
        with:
          dotnet-version: 6.0.x
      - name: force dotnet version
        run: |
          echo '{"sdk":{"version": "${{ steps.dotnet.outputs.dotnet-version }}"}}' > ./global.json
      - name: print
        run: dotnet --list-sdks && dotnet --info
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      # - name: Test
      #   run: dotnet test --no-restore --verbosity normal
